---
title: "データ"
output: html_document
date: "2025-06-03"
---
```{r}
if (!require(duckdb)) install.packages("duckdb")
# インメモリデータベースに接続
#con <- dbConnect(duckdb())

# データベースに接続
# (DBを他のプロセスと共有するときは、read_only = TRUEにし書き込みを禁止する。)
con <- dbConnect(duckdb(), dbdir = 'a.duckdb', read_only = FALSE)

# データベースにあるテーブルを表示
```


```{r}
dbListTables(con)
```



```{r}
d <- data.frame(name   = c('Taro', 'Jiro'),
                salary = c(600, 550))

# 既にテーブルが存在している場合は削除
#if ( dbExistsTable(con, 'items') ) dbRemoveTable(con, 'items')

# データベースにテーブルを作成
#【オプション】追記モード： append = T、#上書きモード： overwrite = T
dbWriteTable(con, 'items', d, append = T)

# テーブルからデータを取得
res <- dbGetQuery(con, "SELECT * FROM items")

dbDisconnect(con, shutdown = TRUE)

# 取得したデータを表示
# 本コードでは追記モードにしているのでプログラム実行のたびに同じレコード追加される。
print(res)
```
```{r}
if (!require(nycflights13)) install.packages("nycflights13")
data("flights", package = "nycflights13") # データの取得
```
```{r}
con <- dbConnect(duckdb()) # インメモリデータベースを作成、接続
duckdb_register(con, "flights", flights) # filightsを紐付け（DuckDBのテーブルとして扱う）

res <- dbGetQuery(con,
'SELECT origin, dest, n
  FROM (
    SELECT q01.*, RANK() OVER (PARTITION BY origin ORDER BY n DESC) AS col01
    FROM (
      SELECT origin, dest, COUNT(*) AS n
      FROM flights
      GROUP BY origin, dest
    ) q01
  ) q01
  WHERE (col01 <= 3) ORDER BY origin')

duckdb_unregister(con, "flights")  # fligthtsの紐付け解除
dbDisconnect(con, shutdown = TRUE) # データベースの接続解除
print(res) # 結果表示
```
```{r}
if (!require(tidyverse)) install.packages("tidyverse")
con <- dbConnect(duckdb()) # インメモリデータベースを作成、接続
duckdb_register(con, "flights", flights) # filightsを紐付け（DuckDBのテーブルとして扱う）

# DuckDBライブラリの機能でクエリを表示（show_query）できる。
#tbl(con, 'flights') |> group_by(origin) |> count(dest) |> slice_max(n, n = 3) |> arrange(origin) |> show_query()
tbl(con, 'flights') |> 
  group_by(origin) |> 
  count(dest) |>
  slice_max(n, n = 3) |> 
  arrange(origin) -> res

print(res) # 結果表示

res |> collect() |> as.data.frame() -> d.out # Rオブジェクトにするときはcollect関数を使う。
duckdb_unregister(con, "flights")  # fligthtsの紐付け解除
dbDisconnect(con, shutdown = TRUE) # データベースの接続解除
```
```{r}
library(tidyverse)

d <- data.frame(
  name = c("太郎", "花子", "三郎", "良子", "次郎", "桜子", "四郎", "松子", "愛子"),
  school = c("南", "南", "南", "南", "南", "東", "東", "東", "東"),
  teacher = c("竹田", "竹田", "竹田", "竹田",  "佐藤", "佐藤", "佐藤", "鈴木", "鈴木"),
  gender = c("男", "女", "男", "女", "男", "女", "男", "女", "女"),
  math = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
  reading = c(1, 5, 2, 4, 5, 4, 1, 5, 4) )
```
```{r}
library(tidyverse)

# 学生名と数学の成績だけを抽出
d %>% select(name, math)
```
```{r}
library(tidyverse)

# gender列を除いたデータを取得
d %>% select(-gender)
```
```{r}
library(tidyverse)

# 3～6番目のレコードを取得
d %>% slice(3:6)
```
```{r}
library(tidyverse)

# name列の文字コード順で並べ替え（アルファベット順に近い並び）
d %>% arrange(name)
```
```{r}
d %>% arrange(desc(math))
```
```{r}
d %>% arrange(desc(math), desc(reading))
```
```{r}
d %>% select(name, reading)

```
```{r}
d %>% select(name, reading)
```
```{r}
d %>% summarise(mean_math = mean(math))
```
```{r}
d %>% group_by(teacher) %>% summarise(mean_math = mean(math))
```
```{r}
d %>% filter(gender == "女") %>% select(name, math)

```
```{r}
d %>% filter(school == "南", gender == "男") %>% select(name, reading)

```
```{r}
d %>% group_by(teacher) %>%
  filter(n() >= 3) %>%
  ungroup()
```
```{r}
d %>% mutate(total = math + reading)
```
```{r}
d %>% mutate(math100 = math / 5 * 100)
```


